version: 0.2
env:
  variables:
    AWS_REGION: $AWS_REGION
    AWS_ACCOUNT_ID: $AWS_ACCOUNT_ID
    AWS_SERVICE_NAME: .dkr.ecr.
    AWS_DOMAIN_NAME: .amazonaws.com
    ECR_REPOSITORY: $ECR_REPOSITORY
phases:
  pre_build:
    commands:
      - aws --version
      - REPOSITORY_URI=117373655737.dkr.ecr.us-east-1.amazonaws.com/docusaurus
      - echo Logging in to Amazon ECR...
      - echo $REPOSITORY_URI
      - aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $REPOSITORY_URI
      - aws ecr describe-repositories --repository-names $ECR_REPOSITORY || aws ecr create-repository --repository-name $ECR_REPOSITORY
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=${COMMIT_HASH:=latest}
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...          
      - docker build -t $REPOSITORY_URI:latest .
      - docker tag $REPOSITORY_URI:latest $REPOSITORY_URI:$IMAGE_TAG
  post_build:
    commands:
      - echo Build completed
      - echo Pushing the Docker images...
      - docker push $REPOSITORY_URI:latest
      - docker push $REPOSITORY_URI:$IMAGE_TAG
      - echo Writing definitions file...
      - printf '[{"name":"docusaurus-ui","imageUri":"%s"}]' $REPOSITORY_URI:$IMAGE_TAG > imagedefinitions.json
      - cat imagedefinitions.json
artifacts:
    files:
      - imagedefinitions.json
